import localFont from "next/font/local";
import "./globals.css";
import type { ComponentProps } from "../types";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: ComponentProps) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
